service:
  name:  todostest

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local


custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
  bucket: todostest

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
    - Effect: Allow
      Action: 
        - S3:*
      Resource: "*"

functions:
  generateTodos:
    handler: src/functions/todoPost.handle
    events:
      - http:
          path: /todos/{userid}
          method: POST
          cors: true
    iamRoleStatements:
    - Effect: Allow
      Actions:
        - dynamodb:Query
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${self.provider.region}:*:tables/todostest"
  verifyTodos:
    handler: src/functions/todoGet.handle
    events:
      - http:
          path: /todos/{userid}
          method: GET
          cors: true
    iamRoleStatements:
    - Effect: Allow
      Actions:
        - dynamodb:Query
      Resource: "arn:aws:dynamodb:${self.provider.region}:*:tables/todostest"

resources:
  Resources:
    dbCertificateUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todostest
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: userid
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: userid
            KeyType: RANGE